import 'package:supabase_flutter/supabase_flutter.dart';
import '../../domain/entities/child.dart';
import '../../domain/repositories/child_repository.dart';

class ChildRepositoryImpl implements ChildRepository {
  final SupabaseClient _supabase;

  ChildRepositoryImpl(this._supabase);

  /// Получить ID текущего пользователя или null, если не аутентифицирован
  String? get _userId => _supabase.auth.currentUser?.id;

  /// Получить ID текущего пользователя или выбросить исключение
  String get _requireUserId {
    final userId = _userId;
    if (userId == null) {
      throw Exception('User not authenticated');
    }
    return userId;
  }

  @override
  Future<List<Child>> getChildren() async {
    final userId = _userId;
    if (userId == null) return [];

    final response = await _supabase
        .from('children')
        .select()
        .eq('user_id', userId)
        .order('created_at', ascending: false);

    return (response as List)
        .map((json) => Child.fromJson(json as Map<String, dynamic>))
        .toList();
  }

  @override
  Future<Child> getChildById(String id) async {
    final userId = _requireUserId;

    final response = await _supabase
        .from('children')
        .select()
        .eq('id', id)
        .eq('user_id', userId)
        .single();

    return Child.fromJson(response);
  }

  @override
  Future<Child> createChild(Child child) async {
    final userId = _requireUserId;

    final childData = child.toJson();
    // Remove fields that should be generated by the database
    childData.remove('id');
    childData.remove('created_at');
    childData.remove('updated_at');
    childData['user_id'] = userId;

    final response =
        await _supabase.from('children').insert(childData).select().single();

    return Child.fromJson(response);
  }

  @override
  Future<Child> updateChild(Child child) async {
    if (child.id == null) {
      throw Exception('Child ID is required for update');
    }

    final userId = _requireUserId;

    final response = await _supabase
        .from('children')
        .update(child.toJson())
        .eq('id', child.id!)
        .eq('user_id', userId)
        .select()
        .single();

    return Child.fromJson(response);
  }

  @override
  Future<void> deleteChild(String id) async {
    final userId = _requireUserId;

    await _supabase
        .from('tales.children')
        .delete()
        .eq('id', id)
        .eq('user_id', userId);
  }
}
